<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accept cookies' => 'Cookies akzeptieren',
    'Column' => 'Spalte',
    'Error' => 'Fehler',
    'External content' => 'Externer Inhalt',
    'Full width' => 'Volle Breite',
    'Internal Server Error' => 'Interner Serverfehler',
    'Page not found' => 'Seite nicht gefunden',
    'Permission denied' => 'Zugriff verweigert',
    'Please accept cookies to load this external video. More information can be found in our {policy}.' => 'Bitte akzeptieren Sie unsere Cookies, um ein externes Video zu laden. Weitere Informationen finden Sie in unserer {policy}.',
    'Please get in touch with {email}' => 'Bitte kontaktieren Sie uns unter {email}',
    'The requested page was not found' => 'Die angeforderte Seite wurde nicht gefunden',
    'privacy policy' => 'Datenschutzerklärung',
];
